package com.dearfloral.common.enums;

public enum CustomOrderStatus {
    PENDING_DEPOSIT,
    PENDING_DEPOSIT_VERIFICATION,
    DEPOSITED,
    WAITING_FLOWER_REVIEW,
    WAITING_FLOWER_RECEIPT,
    IN_PROGRESS,
    WAITING_DEMO_FEEDBACK,
    WAITING_REMAINING_PAYMENT,
    WAITING_REMAINING_PAYMENT_VERIFICATION,
    DELIVERING,
    WAITING_REFUND_INFO,
    WAITING_REFUND,
    REFUNDED,
    COMPLETED,
    CANCELED
}
